### ISSUE TITLE
Memory.tmp not initialized

### ISSUE THREAD

**Issue by ghost** [Akuukis/screeps#1]
Memory.tmp.pois = Memory.tmp.pois||[];
                                ^
TypeError: Cannot read property 'pois' of undefined
    at main:1028:30

Solution:
if(!Memory.tmp){ Memory.tmp={}; };

**Comment by Akuukis** [comment]
Thanks! done in 047a689b0ac1fb5cdebc8f76d771f4c62ed88bc5
