### ISSUE TITLE
Cannot read property 'pos' of null

### ISSUE THREAD

**Issue by Yrlish** [Akuukis/screeps#11]
I got a few hundred of these error messages today. But eventually, they disappeared, no idea why.

```
squad:5
        if(!squad.name){ squad.name="mine_"+gobi(id).pos.roomName+"-"+gobi(id).pos.x+"-"+gobi(id).pos.y; };
                                                    ^
TypeError: Cannot read property 'pos' of null
    at Object.module.exports.doMine (squad:5:47)
    at Array.forEach (native)
    at Object.module.exports.loop (main:32:34)
    at __mainLoop:1:52
```

**Comment by Akuukis** [comment]
`id` here points to energy source. Maybe you have lost vision of it?

**Comment by Akuukis** [comment]
For you and others I made a 'legacy' branch that has everything non-working removed for easier understanding, while I will keep working on the big idea in 'dev' branch.
Please check out that branch. As it is legacy code i am closing this ticket.
