### ISSUE TITLE
TypeError: Cannot read property 'energy' of undefined

### ISSUE THREAD

**Issue by consultoriadigital-pt** [Akuukis/screeps#14]
Hello, I tried to start the script in dev branch in a fresh room and I got the following error:

TypeError: Cannot read property 'energy' of undefined
    at new Bazaar (economy:143:21)
    at economy:173:20
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at squad:4:33

Am I doing something wrong?

**Comment by Akuukis** [comment]
Not really, its just that `dev` branch is broken all over with plenty of unimplemented dreams. Check out `legacy` branch - that should work fine for a single room ;)

**Comment by Akuukis** [comment]
Updated README to clarify this.
