### ISSUE TITLE
Hard coded room breaks execution

### ISSUE THREAD

**Issue by ghost** [Akuukis/screeps#2]
main:1035
        sources = Game.rooms.E5S6.find(FIND_SOURCES);
                                 ^
TypeError: Cannot read property 'find' of undefined
    at main:1035:28

-> Access for room E5S6 is not accessible for other players, which breaks poliy 1: 
No hardcoded places, rates, targets, etc.

**Comment by Akuukis** [comment]
I was just doing testing, but in a brutal way while alone. Next time I will branch in order not to break `develop` functionality in case someone uses it.

Solved by ebaedee90e8f7f2e2d28346e15c73eebbfcc58f4
