### ISSUE TITLE
dtask:51 Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by 89gsc** [Akuukis/screeps#8]
Got this error on an existing colony any advise? 

dtask:51
            for(var i in Game.flags){ if(Game.flags[i].room.name==roomName){ Game.flags[i].remove(); }; };
                                                           ^
TypeError: Cannot read property 'name' of undefined
    at module.exports.overlayNetwork (dtask:51:51)
    at eval (eval at <anonymous> (dtask:10:35), <anonymous>:1:1)
    at Object.module.exports.doNext (dtask:10:12)
    at Object.module.exports.loop (main:53:9)
    at __mainLoop:1:52

**Comment by 89gsc** [comment]
This problem seemed to be caused possibly by re-spawning in the main world as it had the old city and old room referenced in memory? 

I put that if statement in some try brackets and it seems to continue running as normal, any ideas?

**Comment by Akuukis** [comment]
Hi,

Looks similar to #5 that was fixed in `develop` branch. Can you please checkout `develop` and see if it works?

**Comment by Yrlish** [comment]
I too has this problem. I'm spawning in a brand new room, with nothing in RawMemory (returns "{}"), I get this error:

```
[5:03:46 PM]dtask:51
            for(var i in Game.flags){ if(Game.flags[i].room.name==roomName){ Game.flags[i].remove(); }; };
                                                           ^
TypeError: Cannot read property 'name' of undefined
    at module.exports.overlayNetwork (dtask:51:51)
    at eval (eval at <anonymous> (dtask:10:35), <anonymous>:1:1)
    at Object.module.exports.doNext (dtask:10:12)
    at Object.module.exports.loop (main:53:9)
    at __mainLoop:1:52
```

**Comment by Yrlish** [comment]
When I got rid off every flag in Game.flags, it worked.

EDIT: Running latest **develop**.
