### ISSUE TITLE
transNaN

### ISSUE THREAD

**Issue by Yrlish** [Akuukis/screeps#9]
My first creep with role "trans" got named "transNaN". Two times (different rooms).

It works fine with it, but it's wrong and not intended. ^^

**Comment by Akuukis** [comment]
Hi!
Hmm, that's weird. At least it works fine! If you want to fix it, then most probably that is caused by function, who assigns numbers and instead of returning 0 returns NaN.

**Comment by Akuukis** [comment]
I got back to this project. For you and others I made a 'legacy' branch that has everything non-working removed for easier understanding, while I will keep working on the big idea in 'dev' branch.
